Repository what-surv/what-surv-frontend, pull requests merged in 2024-04, with the labels that each got.

#132 122 qa 2차 대응
  package.json
  src/App.tsx
  src/api/IndexApi.ts
  src/api/LikeApi.ts
  src/history/History.ts
  src/main.tsx
  src/molecules/post/write/PostEndDate.tsx
  src/molecules/post/write/PostInputContent.tsx
  src/molecules/post/write/PostSelectDropdown.tsx
  src/organisms/post/mypage/LikePostList.tsx
  src/organisms/post/mypage/MyPostsList.tsx
  src/organisms/post/write/PostSelectContent.tsx
  src/pages/myPages/InterestArticlesPage.tsx
  src/pages/myPages/MyWritePostPage.tsx
  src/pages/myPages/Setting.tsx
  src/pages/post/PostEditPage.tsx
  src/pages/post/PostViewPage.tsx
  src/pages/post/PostWritePage.tsx
  src/stories/appbar/Appbar.tsx
  src/stories/dropdown/Dropdown.tsx
  tailwind.config.js
  yarn.lock
Labels: bug

#136 131 qa 수정
  src/api/IndexApi.ts
  src/api/LikeApi.ts
  src/assets/img-main-banner-1-mb.png
  src/assets/img-main-banner-2-mb.png
  src/assets/img-main-banner-3-mb.png
  src/component/MainSwiper.tsx
  src/index.css
  src/organisms/CardList.tsx
  src/pages/Index.tsx
  src/pages/login/Login.tsx
  src/pages/login/UserInformationsPage.tsx
  src/stories/card/Card.tsx
  src/stories/loginpages/birthdayWrite/BirthDayWriteInput.tsx
  vite.config.ts
Labels: bug

#138 122 qa 2차 대응
  src/api/IndexApi.ts
  src/atoms/post/SelectDate.tsx
  src/molecules/post/write/PostInputContent.tsx
  src/organisms/post/mypage/LikePostList.tsx
  src/organisms/post/mypage/MyPostsList.tsx
  src/organisms/post/view/PostContentView.tsx
  src/organisms/post/write/DropdownValue.ts
  src/pages/misc/Nodata.tsx
  src/pages/myPages/Setting.tsx
  src/pages/post/PostEditPage.tsx
  src/pages/post/PostViewPage.tsx
  src/pages/post/PostWritePage.tsx
Labels: bug

#147 140 조아요 기능 만들기
  .github/workflows/chromatic.yml
  src/api/IndexApi.ts
  src/molecules/post/view/CommentWithButton.tsx
  src/molecules/post/write/PostInputContent.tsx
  src/molecules/post/write/PostSelectDropdown.tsx
  src/organisms/CardList.tsx
  src/organisms/post/mypage/LikePostList.tsx
  src/organisms/post/mypage/MyPostsList.tsx
  src/organisms/post/view/PostContentView.tsx
  src/organisms/post/view/UserInfoWithComment.tsx
  src/organisms/post/write/PostSelectContent.tsx
  src/pages/myPages/Setting.tsx
  src/pages/post/PostViewPage.tsx
  src/pages/post/PostWritePage.tsx
  src/store/store.ts
  src/stories/dropdown/Dropdown.tsx
Labels: bug

#153 fix. 게시글 상세 조회 시 삭제된 유저 댓글 에러 수정
  src/molecules/post/view/UserInfo.tsx
  src/organisms/post/view/UserInfoWithComment.tsx
Labels: bug

#159 157 탈퇴한 유저에 대한 댓글대댓글 처리 오류 해결
  src/molecules/post/view/CommentWithButton.tsx
  src/pages/post/PostViewPage.tsx
Labels: bug

#160 156 increase lighthouse score
  package.json
  src/App.tsx
  src/api/IndexApi.ts
  src/assets/banner/img-main-banner-1-mb.png
  src/assets/banner/img-main-banner-1-mb.svg
  src/assets/banner/img-main-banner-1-pc.png
  src/assets/banner/img-main-banner-1-pc.svg
  src/assets/banner/img-main-banner-1-tb.svg
  src/assets/banner/img-main-banner-2-mb.png
  src/assets/banner/img-main-banner-2-mb.svg
  src/assets/banner/img-main-banner-2-pc.png
  src/assets/banner/img-main-banner-2-pc.svg
  src/assets/banner/img-main-banner-2-tb.svg
  src/assets/banner/img-main-banner-3-mb.png
  src/assets/banner/img-main-banner-3-mb.svg
  src/assets/banner/img-main-banner-3-pc.svg
  src/assets/banner/img-main-banner-3-tb.svg
  src/component/MainSwiper.tsx
  src/molecules/post/view/CommentWithButton.tsx
  src/molecules/post/view/EditWithButton.tsx
  src/molecules/post/view/PostInputContentView.tsx
  src/molecules/post/view/ReplyWithButton.tsx
  src/molecules/post/write/EditorBox.tsx
  src/molecules/post/write/PostInputContent.tsx
  src/organisms/ConfirmationModal.tsx
  src/organisms/LoginAlertModal.tsx
  src/organisms/LogoutAlertModal.tsx
  src/organisms/WithdrawalModal.tsx
  src/organisms/post/mypage/CompleteModal.tsx
  src/organisms/post/mypage/LikePostList.tsx
  src/organisms/post/mypage/MyPostsList.tsx
  src/organisms/post/view/UserInfoWithComment.tsx
  src/organisms/post/write/PostSuccessModal.tsx
  src/organisms/post/write/Spinner.tsx
  src/pages/Index.tsx
  src/pages/login/LastPage.tsx
  src/pages/login/TermsOfServiceAgreementPage.tsx
  src/pages/misc/NotFoundPage.tsx
  src/pages/myPages/InterestArticlesPage.tsx
  src/pages/myPages/MyWritePostPage.tsx
  src/pages/myPages/Setting.tsx
  src/pages/post/PostEditPage.tsx
  src/pages/post/PostWritePage.tsx
  src/stories/cardSkeleton/CardSkeleton.tsx
  src/stories/footer/Footer.tsx
  src/stories/indicator/pagination/Pagination.stories.ts
  src/stories/loginpages/genderButton/GenderButton.tsx
  src/toastUI.css
  vite.config.ts
  yarn.lock
Labels: bug

#164 161 사소한 이슈 추가 대응
  src/molecules/post/view/EditWithButton.tsx
  src/molecules/post/view/PostInputContentView.tsx
  src/molecules/post/view/ReplyWithButton.tsx
  src/molecules/post/write/PostInputContent.tsx
  src/organisms/post/view/PostContentView.tsx
  src/organisms/post/view/UserInfoWithComment.tsx
Labels: bug

#167 161 사소한 이슈 추가 대응
  src/api/LikeApi.ts
  src/molecules/post/view/ReplyWithButton.tsx
  src/molecules/post/view/WriteComment.tsx
  src/organisms/post/mypage/LikePostList.tsx
  src/organisms/post/mypage/MyPostsList.tsx
  src/organisms/post/view/UserInfoWithComment.tsx
  src/pages/misc/PrivateRoute.tsx
Labels: wontfix

#171 161 사소한 이슈 추가 대응
  src/molecules/post/view/CommentWithButton.tsx
  src/molecules/post/view/EditWithButton.tsx
  src/molecules/post/write/PostInputContent.tsx
  src/organisms/post/view/UserInfoWithComment.tsx
  src/pages/myPages/InterestArticlesPage.tsx
Labels: invalid

#175 161 사소한 이슈 추가 대응
  src/api/PostApi.ts
  src/molecules/post/view/WriteComment.tsx
  src/organisms/post/view/UserInfoWithComment.tsx
  src/organisms/post/write/DropdownValue.ts
  src/pages/login/SocailButtonsPage.tsx
  src/pages/post/PostViewPage.tsx
Labels: bug
