Repository what-surv/what-surv-frontend, pull requests merged in 2024-03, with the labels that each got.

#58 41 crud 페이지 뒤로가기게시글 작성 완료 시 modal popup 구현
  src/App.tsx
  src/assets/account-fill.svg
  src/assets/account-outline.svg
  src/assets/arrow-up-circle.svg
  src/assets/delete.svg
  src/assets/edit-line.svg
  src/atoms/post/CommentButton.tsx
  src/molecules/post/view/CommentWithButton.tsx
  src/molecules/post/view/PostInputContentView.tsx
  src/molecules/post/view/PostSelectContentView.tsx
  src/molecules/post/view/ReplyWithButton.tsx
  src/molecules/post/view/UserInfo.tsx
  src/molecules/post/write/EditorBox.tsx
  src/molecules/post/write/PostEndDate.tsx
  src/molecules/post/write/PostInputContent.tsx
  src/molecules/post/write/PostSelectDropdown.tsx
  src/organisms/post/view/PostContentView.tsx
  src/organisms/post/view/UserInfoWithComment.tsx
  src/organisms/post/write/ConfirmationModal.tsx
  src/organisms/post/write/DropdownValue.ts
  src/organisms/post/write/PostSelectContent.tsx
  src/organisms/post/write/PostSuccessModal.tsx
  src/pages/Index.tsx
  src/pages/View.tsx
  src/pages/post/PostViewPage.tsx
  src/pages/post/PostWritePage.tsx
  src/stories/appbar/Appbar.tsx
  src/stories/assets/ic_reply.svg
  src/stories/card/Card.tsx
Labels: enhancement

#71 67 edit design to after design qa
  src/api/IndexApi.ts
  src/molecules/post/view/CommentWithButton.tsx
  src/molecules/post/view/PostInputContentView.tsx
  src/molecules/post/view/UserInfo.tsx
  src/molecules/post/view/WriteComment.tsx
  src/molecules/post/write/PostInputContent.tsx
  src/organisms/ConfirmationModal.tsx
  src/organisms/post/view/UserInfoWithComment.tsx
  src/organisms/post/write/DropdownValue.ts
  src/pages/Index.tsx
  src/pages/post/PostViewPage.tsx
  src/pages/post/PostWritePage.tsx
  src/stories/dropdown/Dropdown.tsx
Labels: enhancement

#81 74 header account hover 시 목록 나오도록 구현
  .storybook/main.ts
  package.json
  src/atoms/Input.tsx
  src/molecules/post/view/WriteComment.tsx
  src/pages/myPages/Setting.tsx
  src/pages/post/PostViewPage.tsx
  src/stories/appbar/Appbar.stories.ts
  src/stories/appbar/Appbar.tsx
  src/stories/appbar/util.ts
  src/stories/assets/edit-black.svg
  src/stories/assets/heart-black.svg
  src/stories/assets/setting.svg
  src/stories/dropdown/Dropdown.tsx
  yarn.lock
Labels: enhancement

#87 feact. google analytics 연동
  package.json
  src/App.tsx
  src/ga/RouteChangeTracker.tsx
  yarn.lock
Labels: enhancement

#94 89 게시글 수정하기 기능 완성하기
  src/api/Posttypes.ts
  src/molecules/post/write/EditorBox.tsx
  src/molecules/post/write/PostInputContent.tsx
  src/organisms/post/view/PostContentView.tsx
  src/organisms/post/write/DropdownValue.ts
  src/organisms/post/write/PostSelectContent.tsx
  src/pages/myPages/Setting.tsx
  src/pages/post/PostEditPage.tsx
  src/pages/post/PostWritePage.tsx
  src/stories/dropdown/Dropdown.tsx
Labels: bug, enhancement

#102 95 마이페이지 input 변경 및 post 기능 추가
  src/api/Posttypes.ts
  src/atoms/post/SelectDate.tsx
  src/organisms/post/mypage/CompleteModal.tsx
  src/pages/Index.tsx
  src/pages/myPages/Setting.tsx
  src/pages/post/PostEditPage.tsx
  src/stories/textfield/Textfield.tsx
Labels: enhancement

#107 fix. remove react-hook-form devtools
  src/App.tsx
  src/ga/RouteChangeTracker.tsx
  src/pages/myPages/Setting.tsx
  src/pages/post/PostEditPage.tsx
  src/pages/post/PostWritePage.tsx
Labels: bug

#109 108 fix 댓글 삭제 401 에러
  src/molecules/post/view/CommentWithButton.tsx
  src/molecules/post/view/PostSelectContentView.tsx
  src/molecules/post/write/EditorBox.tsx
  src/organisms/post/view/UserInfoWithComment.tsx
  src/stories/footer/Footer.tsx
Labels: bug

#116 111 fix qa 이슈사항 수정
  package.json
  src/atoms/post/SelectDate.tsx
  src/index.css
  src/molecules/post/view/CommentWithButton.tsx
  src/molecules/post/view/EditWithButton.tsx
  src/molecules/post/view/ReplyWithButton.tsx
  src/molecules/post/view/WriteComment.tsx
  src/molecules/post/write/EditorBox.tsx
  src/molecules/post/write/PostSelectDropdown.tsx
  src/organisms/post/mypage/LikeCardList.tsx
  src/organisms/post/mypage/LikePostList.tsx
  src/organisms/post/mypage/MyPostsList.tsx
  src/organisms/post/view/UserInfoWithComment.tsx
  src/organisms/post/write/PostSelectContent.tsx
  src/organisms/post/write/PostSuccessModal.tsx
  src/pages/myPages/InterestArticlesPage.tsx
  src/pages/myPages/Setting.tsx
  src/pages/post/PostEditPage.tsx
  src/pages/post/PostWritePage.tsx
  src/store/store.ts
  src/stories/dropdown/Dropdown.tsx
  yarn.lock
Labels: bug

#119 111 fix qa 이슈사항 수정
  src/atoms/post/SelectDate.tsx
  src/molecules/post/view/WriteComment.tsx
  src/molecules/post/write/EditorBox.tsx
  src/molecules/post/write/PostSelectDropdown.tsx
  src/organisms/post/mypage/CompleteModal.tsx
  src/organisms/post/mypage/LikePostList.tsx
  src/organisms/post/mypage/MyPostsList.tsx
  src/organisms/post/view/PostContentView.tsx
  src/organisms/post/write/PostSelectContent.tsx
  src/pages/myPages/Setting.tsx
  src/pages/post/PostEditPage.tsx
  src/pages/post/PostViewPage.tsx
  src/pages/post/PostWritePage.tsx
  src/store/store.ts
  src/stories/dropdown/Dropdown.tsx
Labels: bug

#121 fix. Appbar로그인버튼 추가
  src/stories/appbar/Appbar.tsx
Labels: bug

#123 122 qa 2차 대응
  package.json
  src/index.css
  src/molecules/post/write/EditorBox.tsx
  src/organisms/CardList.tsx
  src/organisms/post/write/Spinner.tsx
  src/pages/Index.tsx
  src/stories/dropdown/Dropdown.tsx
  src/toastUI.css
  yarn.lock
Labels: bug

#126 122 qa 2차 대응
  src/component/MainSwiper.tsx
  src/molecules/post/view/CommentWithButton.tsx
  src/molecules/post/view/WriteComment.tsx
  src/molecules/post/write/EditorBox.tsx
  src/organisms/LoginAlertModal.tsx
  src/organisms/post/mypage/LikePostList.tsx
  src/organisms/post/mypage/MyPostsList.tsx
  src/pages/myPages/MyWritePostPage.tsx
  src/pages/post/PostViewPage.tsx
Labels: bug
