Repository what-surv/what-surv-frontend, pull requests merged in 2024-02, with the labels that each got.

#19 ignore pnp.cjs
  .gitignore
Labels: bug

#23 git rm --cached pnpcjs
  .pnp.cjs
Labels: bug, enhancement

#42 41 crud 페이지 뒤로가기게시글 작성 완료 시 modal popup 구현
  index.html
  package.json
  src/App.tsx
  src/assets/modal-check.svg
  src/molecules/post/PostInputContent.tsx
  src/organisms/post/ConfirmationModal.tsx
  src/organisms/post/PostSelectContent.tsx
  src/organisms/post/PostSuccessModal.tsx
  src/pages/post/PostWritePage.tsx
  src/store/store.ts
  src/stories/appbar/Appbar.tsx
  src/stories/dropdown/Dropdown.tsx
  src/stories/tabbar/Tabbar.tsx
  tailwind.config.js
  yarn.lock
Labels: enhancement

#51 edit responsive design Tabbar/Appbar components
  src/stories/appbar/Appbar.stories.ts
  src/stories/appbar/Appbar.tsx
  src/stories/assets/close-circle.svg
  src/stories/assets/close.svg
  src/stories/assets/logo-identity.svg
  src/stories/card/Card.tsx
  src/stories/dropdown/Dropdown.tsx
  src/stories/tabbar/Tabbar.stories.ts
  src/stories/tabbar/Tabbar.tsx
Labels: documentation
